package com.swj.crawler.mapper;

import com.swj.crawler.model.TbSpu;

import java.util.List;

public interface TbSpuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler..tb_spu
     *
     * @mbg.generated Mon May 18 17:28:20 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler..tb_spu
     *
     * @mbg.generated Mon May 18 17:28:20 CST 2020
     */
    int insert(TbSpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler..tb_spu
     *
     * @mbg.generated Mon May 18 17:28:20 CST 2020
     */
    TbSpu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler..tb_spu
     *
     * @mbg.generated Mon May 18 17:28:20 CST 2020
     */
    List<TbSpu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler..tb_spu
     *
     * @mbg.generated Mon May 18 17:28:20 CST 2020
     */
    int updateByPrimaryKey(TbSpu record);
}