spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
#    仓库分支
      label: master
      server:
        git:
          uri: https://github.com/1056438464/spring-cloud-config
#          目录
          search-paths: respo
          username:
          password:
#          访问地址：https://github.com/1056438464/yml文件名/分支名

#默认端口，不能修改，如果要修改需要新建一个bootstrap.yml文件中 写如server：port：端口号
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/