spring:
  application:
    name: spring-boot-amqp
  rabbitmq:
    host: 47.98.131.180
    port: 5672
    username: rabbit
    password: 123456
    # 一次只发送一条数据给消费者
    listener:
      direct:
        prefetch: 1
