spring:
  application:
    name: spring-boot-amqp
  rabbitmq:
    host: 47.98.131.180
    port: 5672
    username: rabbit
    password: 123456
    listener:
      simple:
#      采用手动应答
        acknowledge-mode: manual
#        当前监听容器数
        concurrency: 1
#        最大数
        max-concurrency: 1
#        是否支持重试
        retry:
          enabled: true
