server:
  port: 9015
spring:
  application:
    name: config-centre
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1056438464/swj-parent
          username: 1056438464@qq.com
          password: 192310swj...
          timeout: 5000
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            # 熔断器超时时间，默认：1000/毫秒
            timeoutInMilliseconds: 2000
workerId: 0
datacenterId: 0