spring:
  application:
    name: itoken-eureka
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://http://192.168.240.131:8761/eureka/,http://http://192.168.240.131:8861/eureka/,http://http://192.168.240.131:8961/eureka/



management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info