package com.swj.crawler.model;

public class Log {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler..log.id
     *
     * @mbg.generated Mon May 18 16:36:02 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler..log.user_id
     *
     * @mbg.generated Mon May 18 16:36:02 CST 2020
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler..log.id
     *
     * @return the value of crawler..log.id
     * @mbg.generated Mon May 18 16:36:02 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler..log.id
     *
     * @param id the value for crawler..log.id
     * @mbg.generated Mon May 18 16:36:02 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler..log.user_id
     *
     * @return the value of crawler..log.user_id
     * @mbg.generated Mon May 18 16:36:02 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler..log.user_id
     *
     * @param userId the value for crawler..log.user_id
     * @mbg.generated Mon May 18 16:36:02 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}