package com.swj.crawler.mapper.sharding;

import com.swj.crawler.model.Log;

import java.util.List;

public interface LogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler..log
     *
     * @mbg.generated Mon May 18 16:36:02 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler..log
     *
     * @mbg.generated Mon May 18 16:36:02 CST 2020
     */
    int insert(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler..log
     *
     * @mbg.generated Mon May 18 16:36:02 CST 2020
     */
    Log selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler..log
     *
     * @mbg.generated Mon May 18 16:36:02 CST 2020
     */
    List<Log> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler..log
     *
     * @mbg.generated Mon May 18 16:36:02 CST 2020
     */
    int updateByPrimaryKey(Log record);
}